### ISSUE TITLE
Crash when unlinked IO Blocks touch AE components

### ISSUE THREAD

**Issue by KirinDave** [dmillerw/RemoteIO#15]
Using RemoteIO near unbound AE components is dangerous. With 1.9.1-b16:

```
java.lang.NullPointerException
        at appeng.api.DimentionalCoord.<init>(DimentionalCoord.java:21)
        at com.dmillerw.remoteIO.block.tile.TileIO.findRemoteSide(TileIO.java:670)
        at appeng.common.grid.GridEnumeration.update(GridEnumeration.java:429)
        at appeng.common.grid.MEGridEvents.tickStart(MEGridEvents.java:244)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:295)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

Full crash log here: http://pastebin.com/mcASTPdS

**Comment by CoryManson** [comment]
Hi Dmiller.

Any idea when the next build will be out to include this fix? I've ran into this crash a few times and the only way to solve it is to boot the server without remoteIO, causing a small amount of loss.

Thanks :)

**Comment by dmillerw** [comment]
Released!

**Comment by CoryManson** [comment]
Thank you! XD

**Comment by Slind14** [comment]
whats an unlinked io block ?

**Comment by dmillerw** [comment]
You're running an old version. Grab 1.9.3a which has this bug fixed

**Comment by Slind14** [comment]
I know and I updated and it is fixed. But I´m still wondering what caused it.

**Comment by dmillerw** [comment]
Mistake on my part

**Comment by Slind14** [comment]
np, I would have answered the same, I should have put more into the question. Do you knwo what casued it or what is meant by 'unlinked IO Blocks' ?
